apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: demo-app
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 60s
    count: 5
    successCondition: result[0] >= 0.95
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(istio_requests_total{reporter="destination",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m])) /
          sum(rate(istio_requests_total{reporter="destination",destination_service=~"{{args.service-name}}"}[5m])) 