apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
- namespace.yaml
- configmap.yaml
- mock-backend-deployment.yaml
- argo-rollout.yaml
- services.yaml
- istio-gateway.yaml
- istio-virtualservice.yaml
- istio-destinationrule.yaml
- analysis-template.yaml

